ccflags-y += -DCONFIG_TOUCHSCREEN_JADARD_DEBUG=y
ccflags-y += -DCONFIG_TOUCHSCREEN_JADARD_SORTING=y


# Makefile for the Jadard touchscreen drivers.
obj-y += jadard_module.o
obj-y += jadard_ic_JD9366TP.o
obj-y += jadard_common.o jadard_platform.o
obj-y += jadard_debug.o
obj-y += jadard_sorting.o
#obj-y += jadard_hid.o

